### ISSUE TITLE
Object detection with spiking nets

### ISSUE THREAD

**Issue by YangBain** [jotia1/spiking-net-tensorflow#1]
Hi,
I see that you use tensorflow to implement spiking net. So, could you think it can realize the object detection using spiking neural network or do you know how to use spiking neural network do regression?
Thank you very much.

**Comment by jotia1** [comment]
This is probably the most advanced example of image classification using spiking nets I can think of off the top of my head [https://arxiv.org/pdf/1611.01421.pdf](https://arxiv.org/pdf/1611.01421.pdf) this isn't really the right place to be asking this question though. Last time I checked the Masquelier lab generally seems to have some of the most promising (practical) work in that space.
